### ISSUE TITLE
Config Changes Not Being Saved

### ISSUE THREAD

**Issue by Wildcat1** [homebridge-plugins/homebridge-camera-ffmpeg#579]
**Describe The Bug:**
Starting in 2.0.x seeing that any changes to cameras after initial setup do not get reflected in config. **NOTE: Seeing this in the release version of 2.0.x and the beta**

**To Reproduce:**

Using 2.0.x add a camera in with a set criteria (regular -re -i {stream} etc). 

1. After saving and rebooting Homebridge go back into the Config or Plugins, Settings and adjust a parameter, save, reboot again. 
2. After doing this I find that the config is showing the previous (original) version, not updating the changes you made. SO for example if you change the IP address in step 1 and rebooting, the IP address is not updated. 
3. Again this happens whether you are using the Plugins / Settings option to update or directly updating the config.JSON
4. What is strange is that if I remove the camera from Plugins / Settings, save, reboot then add from scratch, that update is reflected fine but cannot edit it afterwards.

**Expected behavior:**
Expect this to update the config.JSON and the camera-ffmpeg plugin to read the updated config

**Logs:**
Not seeing anything in the logs that pinpoints this issue currently but happy to provide. 

**Screenshots**
So here is an example. When I run v2.0.x here is what the logs show when accessing the camera:

[6/29/2020, 4:48:41 PM] [Camera-ffmpeg] ffmpeg -rtsp_transport http -re -i rtsp://xxxxxxx:xxxxxxx@192.168.xx.xx:554/cam/realmonitor?channel=1&subtype=0 -t 1 -vf scale=1280:720 -f image2 -

HOWEVER, here is what the Plugins / Settings section shows (notice the lack of -rtsp_transport in the config):

![Screenshot Of Plugins Settings For Camera FFMPEG](https://user-images.githubusercontent.com/388424/86064144-a00f3c80-ba29-11ea-8414-6249879e06fc.jpg)

Same can be said if you look at the config.JSON therefore its as if after initial setup of v2.0.x that NO changes/updates even in the JSON are being read by the plugin

![Screenshot of Config JSON For Camera FFMPEG](https://user-images.githubusercontent.com/388424/86064153-a3a2c380-ba29-11ea-944a-dddac90d212a.jpg)

Here is what is shown in the Homebridge-UI logs which shows the config.json is being saved and again the config file itself reflects those changes BUT camera-ffmpeg is not reading them:

[6/29/2020, 5:04:21 PM] [Config] Changes to config.json saved.
[1593471861811] INFO  (90189 on mycomputer.localdomain): request completed
    reqId: 10
    res: {
      "statusCode": 201

```

**Homebridge Config:**

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: v2.0.2=beta13 but appeared on all versions of 2.0.x tested so far
* **Homebridge Config UI X Plugin Version**: v4.23.2
* **Operating System**: macOS

**Comment by dankokp** [comment]
I was able to reproduce it too. Was playing with different params for hours to find the best set and in the end realized I didn't even change anything 😭

**Comment by teymur1988** [comment]
I’m having the same issue. Rolled back to 1.3.0

**Comment by isramos** [comment]
I experienced the same issue. I think I found a temporary workaround which is to change the camera name when you make a change.  For example, I renamed "Cam Driveway" to "Cam Driveway2" to force changes to be picked up.

**Comment by Supereg** [comment]
Is this only happening on the latest version of camera-ffmpeg? Meaning is the plugin really the cause of this?
Cause plugins should not be involved with writing or reading the configuration file directly (some do nevertheless, but that's definitely not advised).

**Comment by longzheng** [comment]
I've also reproduced this issue.

I'm able to fix this by removing the cameras in the Homebridge Config UI X > Homebridge Settings > Remove Single Cached Accessory.

**Comment by longzheng** [comment]
> Is this only happening on the latest version of camera-ffmpeg? Meaning is the plugin really the cause of this?
> Cause plugins should not be involved with writing or reading the configuration file directly (some do nevertheless, but that's definitely not advised).

I suspect this was related to how v2.0.0 shows cameras a bridged instead of accessories in v1.3.0. I suspect maybe homebridge caches the config of bridged camera differently to accessories.

**Comment by Supereg** [comment]
https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/blob/585b8f6119b02ea0dd368d84326b5a8770ba94a2/src/index.ts#L53

the plugin stores the configuration made when the camera was first set up and will ignore any further changes to the config made, as it will always just use the stored value

**Comment by ciavez** [comment]
[2020-7-2 19:02:08] [Camera-ffmpeg] FFMPEG: [http @ 0x2f5b360] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[tcp @ 0x2f5ce60] Original list of addresses:
[tcp @ 0x2f5ce60] Address 192.168.8.166 port 554
[tcp @ 0x2f5ce60] Interleaved list of addresses:
[tcp @ 0x2f5ce60] Address 192.168.8.166 port 554
[tcp @ 0x2f5ce60] Starting connection attempt to 192.168.8.166 port 554

[2020-7-2 19:02:08] [Camera-ffmpeg] FFMPEG: [tcp @ 0x2f5ce60] Successfully connected to 192.168.8.166 port 554
[http @ 0x2f5b360] 
[2020-7-2 19:02:08] [Camera-ffmpeg] FFMPEG: request: GET /videoMain HTTP/1.1
User-Agent: Lavf/58.29.100
Range: bytes=0-
Connection: close
Host: 192.168.8.166:554
Icy-MetaData: 1
x-sessioncookie: 6be697ab8b46455f
Accept: application/x-rtsp-tunnelled
Pragma: no-cache
Cache-Control: no-cache



[2020-7-2 19:02:08] [Camera-ffmpeg] FFMPEG: [http @ 0x2f5b360] HTTP error 400 Bad Request

[2020-7-2 19:02:08] [Camera-ffmpeg] FFMPEG: rtsp://ciava:.1Polipo@192.168.8.166:554/videoMain: Input/output error

[2020-7-2 19:02:08] [Camera-ffmpeg] [FFMPEG] ffmpeg exited with code: 1 and signal: null (error)

**Comment by donavanbecker** [comment]
@longzheng should be fixed in last merged.

**Comment by Wildcat1** [comment]
@donavanbecker Latest beta is definitely an improvement to solving the streaming issues BUT I'm noticing that once I add a cam in the latest v2.0.2 beta 39 that any subsequent changes to that cam through the Plugin's\Settings option results in Homebridge not being able to restart as it kicks out the error below. Only way to resolve is to remove Platform, remove cached device and start over. Thoughts on this ? Thanks again 

Cannot add a Service with the same UUID 'xxxxxxxx7xxxxx5xx91' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:276:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at FfmpegPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/index.ts:123:12)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:307:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)

**Comment by donavanbecker** [comment]
> @donavanbecker Latest beta is definitely an improvement to solving the streaming issues BUT I'm noticing that once I add a cam in the latest v2.0.2 beta 39 that any subsequent changes to that cam through the Plugin's\Settings option results in Homebridge not being able to restart as it kicks out the error below. Only way to resolve is to remove Platform, remove cached device and start over. Thoughts on this ? Thanks again

I wonder if you got this be cause the cache was still there. Has it happen again?

**Comment by Wildcat1** [comment]
> > @donavanbecker Latest beta is definitely an improvement to solving the streaming issues BUT I'm noticing that once I add a cam in the latest v2.0.2 beta 39 that any subsequent changes to that cam through the Plugin's\Settings option results in Homebridge not being able to restart as it kicks out the error below. Only way to resolve is to remove Platform, remove cached device and start over. Thoughts on this ? Thanks again
> 
> I wonder if you got this be cause the cache was still there. Has it happen again?

I can literally replicate this over and over. What is weird is it gets into that loop RE: (another service with same UUID) even if I use cam names I had before installing this beta. Steps to reproduce this and then fix are:

**To Cause The Issue:**
1 - Start with fresh plugin (beta 39 and all cached cams removed using Homebridge menu)
2 - Add camera
3 - Restart homebridge
4 - Camera appears without issue
5 - Go back into plugin settings OR config.json and adjust a setting OR add a new camera
6 - Restart Homebridge
7 - Homebridge never restarts getting stuck in the 'another service with same UUID.......' error

**To Fix The Issue**
1 - Go into Plugin\Settings
2 - Remove camera completely
3 - Go to Homebridge menu, remove cached camera(s), this leaves only "platform": "Camera-ffmpeg" in config.json.
4 - Restart Homebridge
5 - Homebridge restarts without issue

The problem of course is 1) somewhere, previous cam names are being stored so seemingly can only be used once and 2) that due to the error being seen, if you need to adjust ANYTHING or add a new camera you will be forced to remove the existing cameras completely, remove cached cams and start from scratch

Thoughts on how to get around this or can be fixed in the plugin @donavanbecker ?

**Comment by Wildcat1** [comment]
@donavanbecker to follow up to my comment above, even just removing cached cam or renaming cam (for update in config) by themselves does not appear to fix the issue. Only removing the cam then removing the cache and restarting does it resolve the restart issue of 'service with same name'. This means that to update or add any extra cams you literally have to start from scratch each time.

**Comment by longzheng** [comment]
I can confirm v2.0.2-beta.39 fixes the config issue for me.

I can
- Edit the video for the existing camera (without renaming the camera)
- Restart homebridge
- View the camera with the new config in Home app immediately

**Comment by Wildcat1** [comment]
> I can confirm v2.0.2-beta.39 fixes the config issue for me.
> 
> I can
> 
> * Edit the video for the existing camera (without renaming the camera)
> * Restart homebridge
> * View the camera with the new config in Home app immediately

@longzheng 
As I am literally seeing the opposite of you:

1) I have to change camera name and remove cache continually every time I update a setting
2) Run into No Response issues at different times

Could you post you config.json specifically cam settings. Call out the cam's you are using (I'm using Dahua & Hik, Axis etc) and then the platform and version you are running on (I'm running macOS Hombridge UI 4.23.2, Node.js Version | v12.16.3, NPM v6.14.5) ? Maybe that will help pinpoint the issue with caching and response too

Thanks

**Comment by longzheng** [comment]
> > I can confirm v2.0.2-beta.39 fixes the config issue for me.
> > I can
> > 
> > * Edit the video for the existing camera (without renaming the camera)
> > * Restart homebridge
> > * View the camera with the new config in Home app immediately
> 
> @longzheng
> As I am literally seeing the opposite of you:
> 
> 1. I have to change camera name and remove cache continually every time I update a setting
> 2. Run into No Response issues at different times
> 
> Could you post you config.json specifically cam settings. Call out the cam's you are using (I'm using Dahua & Hik, Axis etc) and then the platform and version you are running on (I'm running macOS Hombridge UI 4.23.2, Node.js Version | v12.16.3, NPM v6.14.5) ? Maybe that will help pinpoint the issue with caching and response too
> 
> Thanks

Can I suggest you try null out your camera config, save, restart Homebridge, then add it all back in?

```
        {
            "cameras": [
            ],
            "platform": "Camera-ffmpeg"
        }
```

My config.json is very simple. I'm connecting to a Dahua NVR.

```
        {
            "cameras": [
                {
                    "name": "Front door",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.3:554/cam/realmonitor?channel=1&subtype=0",
                        "maxFPS": 20
                    }
                },
                {
                    "name": "Backyard",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.3:554/cam/realmonitor?channel=2&subtype=0",
                        "maxFPS": 20
                    }
                },
                {
                    "name": "Living",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.3:554/cam/realmonitor?channel=3&subtype=0",
                        "maxFPS": 20
                    }
                },
                {
                    "name": "Side",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.3:554/cam/realmonitor?channel=4&subtype=0",
                        "maxFPS": 20
                    }
                },
                {
                    "name": "Laundry",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.3:554/cam/realmonitor?channel=5&subtype=0",
                        "maxFPS": 20
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

In my test, I added `"vflip": true` to my front door camera, restarted homebridge, and then viewed the video and it was flipped. Then I removed `vlip`, restarted homebridge, and then viewed the video and it was normal again.

My versions are

```
Windows 10
homebridge v1.1.1
homebridge-config-ui-x v4.23.2
homebridge-camera-ffmpeg v2.0.2-beta.39
Node.js Version	v14.5.0
Npm Version	v6.4.1
```
