### ISSUE TITLE
[FFMPEG] ffmpeg exited with code: 1 and signal: null (error)

### ISSUE THREAD

**Issue by roomwillow** [homebridge-plugins/homebridge-camera-ffmpeg#603]
**Describe Your Problem:**
Camera appears in home app, however, no thumbnail loads, selecting the camera leads to infinite loading and an error on the homebridge log, was following previously closed issue however updating to the beta and re-naming the camera to something new from a completely cleared config did nothing to help.

![image](https://user-images.githubusercontent.com/67667062/86531009-b7b44e00-be8b-11ea-85a5-3d40e501d205.png)

**Homebridge Config:**

![image](https://user-images.githubusercontent.com/67667062/86531020-d0246880-be8b-11ea-8a1b-841419cc6419.png)

**Environment:**

* **Node.js Version**: 2.18.1
* **NPM Version**: 6.14.15
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: v2.0.2-beta.41
* **Homebridge Config UI X Plugin Version**: 4.23.2
* **Operating System**: Debian Buster

**Comment by Vampier** [comment]
I am observing the same behavior here - but no error message shows up. When a camera can not be found for whatever reason and the homekit screen is requesting a screenshot ffmpeg seems to be stuck, it slows down the rest of the detection - example TP-Link switching and outlets keep the status 'updating'. After removing the offending camera from the config it runs fine (I could have fixed it easily but I was curious what caused the 'updating' issue)

Thanks for the great plugin - since the implementation for the camera to show up straight into the homebridge connected devices it's even easier to setup :)

**Comment by isramos** [comment]
When I had a similar issue, I pasted the FFmpeg command with all parameters in my terminal and I was able to pinpoint the issue. There's a bug in the current version that is suppressing the parameter listing. I just pushed a PR #607 that fixes the logs so that you'll be able to get the parameters. After that update you'll be able to see parameters, such as: 
```
[7/5/2020, 10:02:42 PM] [Camera-ffmpeg] FFMPEG command: ffmpeg -rtsp_transport tcp -re -i rtsp://admin:xxxxx@192.168.1.123:1025/H264?ch=1&subtype=0 -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -benchmark -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 13742952 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params QrDbTPtXQrDbTPtXQrDbTPtX srtp://192.168.1.99:63402?rtcpport=63402&localrtcpport=63402&pkt_size=1316 -loglevel debug
``` 

Then, just the above info in terminal to get a more verbose error.  I believe you should remove the parameters after the -f as that is the output section, and instead, for testing, just use `-f null -`, as seen here https://trac.ffmpeg.org/wiki/Null.

**Comment by donavanbecker** [comment]
#607

**Comment by houser42** [comment]
Hello,
I am seeing the same thing.
`[Camera ffmpeg] [2] [info] frame=  586 fps= 21 q=39.0 size=    1143kB time=00:00:29.58 bitrate= 316.5kbits/s dup=1 drop=0 speed=1.05x    
[7/26/2020, 5:53:02 PM] [Camera ffmpeg] [2] Stopped video stream.
[7/26/2020, 5:53:02 PM] [Camera ffmpeg] [2] ffmpeg exited with code: null and signal: SIGKILL (Expected)
`
Am I correct in understanding this is a bug that will get worked out at some point?
or is there a workaround or fix? Many thanks.

**Comment by Sunoo** [comment]
@houser42 I don't see an error in your log? That's just FFmpeg being closed when you stop viewing the stream.

**Comment by houser42** [comment]
Thanks @Sunoo 
I see. Sorry for being unclear. 
I misread the log and assumed that was the error, as my cameras no longer go to live stream when tapped in the home app. I still get the stills but no streaming. This is on Ubuntu Focal Fossa (20.04.1 LTS).

I believe this happened with one of the last updates of the ffmpeg plugin, or possibly the ol' sudo apt update or something else that broke some dependancy or something. 
Was rather hoping there was a new plugin fix on the way. But life is sometimes not that easy ;)
Probably time to wipe and reinstall I guess... Many thanks.

**Comment by Sunoo** [comment]
@houser42 Do you have multiple network interfaces?

**Comment by houser42** [comment]
If you by "multiple network interfaces" mean there is a mixture ethernet and wifi on the Lan then yes. But this has been rock solid for year and I have lately not touched anything but the typical service updates for all things HB. Are you suspecting something? Thanks. Appreciate it..

**Comment by Sunoo** [comment]
@houser42 In that scenario, it’s basically just random chance if FFmpeg ends up using the correct interface. If you set interfaceName, that should prevent the issue from happening.

**Comment by houser42** [comment]
Thanks @Sunoo,
If that matters, the laptop that runs HB is ethernet only, as is the Apple TV that is the Homehub.
But never tried that... Where do I set that? In config.json for this plugin? Really appreciate the tip!

**Comment by Sunoo** [comment]
@houser42 Yes, it would be in the config.json, there is an example on the main page.

However, if the device Homebridge is running on has a single active interface, that’s probably not your problem.

**Comment by houser42** [comment]
Thanks again @Sunoo,

It seems your advice was correct. I added the network interface of the HB server in json.config and it started working again. Never needed that before. At the the very least, that certainly reset something..
Regardless, many, many thanks!

**Comment by Sunoo** [comment]
Great, glad we got it working.

**Comment by houser42** [comment]
Not as glad as I am ;) Thanks again!

**Comment by IoTPlay** [comment]
Same problem, @Sunoo  Can yougive more instructions to your statement to a "rukee"?

```
I added the network interface of the HB server in json.config
```

**Comment by Sunoo** [comment]
@IoTPlay Current versions of this plugin on current versions of Homebridge no longer have this issue.

**Comment by carismatico78** [comment]
I am still having the issue.  
[11/18/2020, 12:16:43 PM] [Camera FFmpeg] [DrivewayCam] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[11/18/2020, 12:16:43 PM] [Camera FFmpeg] [DrivewayCam] FFmpeg exited with code: 1 and signal: null (Error)
[11/18/2020, 12:16:43 PM] [Camera FFmpeg] [DrivewayCam] Stopped video stream.

**Comment by nossramo** [comment]
I got this working!
"-i rtsp://admin:pass@192.168.1.108/cam/realmonitor?channel=1&subtype=0"
Problem is i was always using my external IP but after adding internal it worked and works ower 4G on HomeKit

**Comment by IoTPlay** [comment]
Thank you.

**Comment by jamesngob** [comment]
I have HIKVision NVR with 5 camera on it. My ffmpeg plugin has been working so far so good until a day ago. It now displayed the error "FFmpeg exited with code: 1 and signal: null (Error)."
I have not altered or changed anything in the setup since over 2 months ago (e.g. the plugin was working fine for the past 2 months)
My homebridge is installed on Ubuntu Server. The homebridge server version is 1.1.7; Node js v14.15.3
What I did:
-I also use internal IP address; I specified the InterfaceName as well. All did not work
-Uninstall/Reinstall the FFmpeg 
-Clean all cache
I still cannot get it to work! What am I missing here?

**Comment by jamesngob** [comment]
> I have HIKVision NVR with 5 camera on it. My ffmpeg plugin has been working so far so good until a day ago. It now displayed the error "FFmpeg exited with code: 1 and signal: null (Error)."
> I have not altered or changed anything in the setup since over 2 months ago (e.g. the plugin was working fine for the past 2 months)
> My homebridge is installed on Ubuntu Server. The homebridge server version is 1.1.7; Node js v14.15.3
> What I did:
> -I also use internal IP address; I specified the InterfaceName as well. All did not work
> -Uninstall/Reinstall the FFmpeg
> -Clean all cache
> I still cannot get it to work! What am I missing here?

I decided to restart the NVR and it worked again! Not sure what happened with it...

**Comment by 1aranzant** [comment]
I have the same issue with my new TAPO c320 camera. 
My others cameras work fine.

**Comment by albilia** [comment]
This also happened to me after I updated the HomeBridge from version 14 to version 16 and had to install all plugins from scratch, with Hikvision Cam model: DS-2CD2542FWD-I.

	

The previous Config were:

{
	"name": "Hikvision",
	"model": "DS-2CD2542FWD-I",
	"serialNumber": "DS-2CD2542FWD-#########",
	"firmwareRevision": "V5.5.5 build 180111",
	"unbridge": false,
	"videoConfig": {
		"source": "-i rtsp://****:****@192.168.10.10:554",
		"maxStreams": 2,
		"maxWidth": 800,
		"maxHeight": 600,
		"maxFPS": 25,
		"audio": true
	}
}

The latest and working Config  After noticing that I used a different model's setting by mistake [Hikvision DS-2CD2423G0-IW]:

 {
 	"name": "Hikvision",
 	"videoConfig": {
 		"source": "-i rtsp://****:****@192.168.10.10:554"
 	}
 }

Thanks to developer @Sunoo  for mentioning the matter here: 
"If maxWidth or maxHeight is set for more than 800 and 600 respectively or not set at all, the camera does not show the live view".
In my case the mistake I made did result in me not being able to see Live View. For the reason that I entered the maxWidth and maxHeight values unnecessarily.
https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Hikvision-DS-2CD2423G0-IW.html 
Now All Good : )

**Comment by Ogdla** [comment]
Hello  
I have the  same  issue on my D-link DCS-930LB that  not  support  rtsp ( working only  on http) .The  motion detection of that camera  working fine  but  i have  this  error message  

[06/05/2023, 13:15:01] [Camera FFmpeg] [Og eyes] Starting video stream: 320 x 240, 20 fps, 299 kbps (AAC-eld)
[06/05/2023, 13:15:01] [Camera FFmpeg] [Og eyes] FFmpeg exited with code: 1 and signal: null (Error)
[06/05/2023, 13:15:01] [Camera FFmpeg] [Og eyes] Stopped video stream.
[06/05/2023, 13:15:08] [Camera FFmpeg] [Og eyes] Failed to fetch snapshot.
[Og eyes] Snapshot request handler provided empty image buffer!
[06/05/2023, 13:15:18] [Camera FFmpeg] [Og eyes] Failed to fetch snapshot.
[Og eyes] Snapshot request handler provided empty image buffer!
[06/05/2023, 13:15:39] [Camera FFmpeg] [Og eyes] Failed to fetch snapshot.
[Og eyes] Snapshot request handler provided empty image buffer!
[06/05/2023, 13:29:43] [Camera FFmpeg] [Og eyes] Failed to fetch snapshot.
[Og eyes] Snapshot request handler provided empty image buffer!
[06/05/2023, 13:43:08] [Camera FFmpeg] [Og eyes] Failed to fetch snapshot.
[Og eyes] Snapshot request handler provided empty image buffer!
[06/05/2023, 13:43:18] [Camera FFmpeg] [Og eyes] Failed to fetch snapshot.
[Og eyes] Snapshot request handler provided empty image buffer!
[06/05/2023, 13:43:33] [Camera FFmpeg] [Og eyes] Starting video stream: 320 x 240, 20 fps, 299 kbps (AAC-eld)
[06/05/2023, 13:43:33] [Camera FFmpeg] [Og eyes] FFmpeg exited with code: 1 and signal: null (Error)
[06/05/2023, 13:43:33] [Camera FFmpeg] [Og eyes] Stopped video stream.
Thks  for your help 

       {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Og eyes",
                    "manufacturer": "D-link",
                    "model": "DSC-930LB",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re  -f mjpeg -i http://user:pwd@192.168.1.20:80/video.cgi",
                        "stillImageSource": "-f mjpeg -i http://user:pwd@192.168.1.20:80/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 20,
                        "vcodec": "h264_omx",
                        "packetSize": 1128,
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}

**Comment by Sunoo** [comment]
Share your full debug log.

**Comment by Ogdla** [comment]
Please  see my previous  post
On VLC I can  reach  my  cam using  the http://user:passwd@192.168.1.20:80/video.cgi

**Comment by Ogdla** [comment]
@sunoo  I have  images  on  ma iPhone  now and it freezes  but  steel have  that  error ;and  i remark that every 10s  the image move  for  a laps of second .

**Comment by rd-pong** [comment]
Same issue here

> @Sunoo I have images on ma iPhone now and it freezes but steel have that error ;and i remark that every 10s the image move for a laps of second .

**Comment by elvisimprsntr** [comment]
BACKGROUND

Dec '22 - HB installed on a Ubuntu server VM (Shutdown)
Feb '23 - Migrated HB to a Ubuntu bare metal MeLE Quieter3C (Celeron N5105) (Shutdown)
Now - Migrated HB to a re-purposed Mac Mini (Core 2 Duo P8600) (Restored from backup) 

ISSUES

1. When I restored from backup, although all the plugins installed, I had to manually install FFMPEG.  (Solved)
2. Now I get the following error message on all my cameras. (Unsolved)
>[Porch] FFmpeg exited with code: 1 and signal: null (Error)

CAM CONFIG EXAMPLE

Note there is no separate snapshot URL defined. 


>{
                    "name": "Porch",
                    "manufacturer": "Lorex",
                    "model": "B451AJ",
                    "serialNumber": "[redacted]",
                    "firmwareRevision": "20220903",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-i rtsp://[redacted]:[redacted]@192.168.69.85:554/cam/realmonitor?channel=1&subtype=1",
                        "audio": true
                    }

OBSERVATIONS

1. HB/HK fetches the snapshots without a problem.  
2. When I attempt to launch the live video, FFMPEG throws the error listed above.

TROUBLE SHOOTING

1. Rebooted all my ATVs and HomePod mini
2. Bound HB to a WLAN interface.  
3. Turned off the Mac Mini and restarted the MeLE Quieter3C (Live video stream working)

QUESTIONS

I have not altered the default FFMPEG video codec "libx264", which I believe is a SW encoder.

1. Is the 2010 Mac mini too underpowered and/or does not support H264 HW accelerated video encoding?
2. Or can I simply switch to a different encoder?

**Comment by BoazHarel1** [comment]
Hello
I have HIKVision NVR with 7 camera on it. I just configured the first link to the firs camera using the ffmpeg plugin.
i can see the camera on the Homekit up and i can see the camera streaming on the VLC using the same RTSP link but on the Home kit app the video is not streaming and the loading while is constantly turning 
on the event log I get the following error line

[29/01/2025, 21:26:47] [PluginUpdate] [Street Camera] Starting video stream: 1280 x 720, native fps, 299 kbps
[29/01/2025, 21:26:47] [PluginUpdate] [Street Camera] FFmpeg exited with code: 234 and signal: null (Error)
[29/01/2025, 21:26:47] [PluginUpdate] [Street Camera] Stopped video stream.

any suggestions?
thanks

**Comment by elvisimprsntr** [comment]
> Hello I have HIKVision NVR with 7 camera on it. I just configured the first link to the firs camera using the ffmpeg plugin. i can see the camera on the Homekit up and i can see the camera streaming on the VLC using the same RTSP link but on the Home kit app the video is not streaming and the loading while is constantly turning on the event log I get the following error line
> 
> [29/01/2025, 21:26:47] [PluginUpdate] [Street Camera] Starting video stream: 1280 x 720, native fps, 299 kbps [29/01/2025, 21:26:47] [PluginUpdate] [Street Camera] FFmpeg exited with code: 234 and signal: null (Error) [29/01/2025, 21:26:47] [PluginUpdate] [Street Camera] Stopped video stream.
> 
> any suggestions? thanks

I am by no means an expert, but could it be a transcoding issue?  Do have the ability to use a different stream or change the video encoding in the NVR? Or tweak the encoding FFMPEG is using?

**Comment by BoazHarel1** [comment]
I’m streaming directly from the camera not through the NVR but anyway it could be transcoding issue however I don’t know what should be defined in the camera video output

**Comment by elvisimprsntr** [comment]
> I’m streaming directly from the camera not through the NVR but anyway it could be transcoding issue however I don’t know what should be defined in the camera video output

1. Increasing the FFMPEG log level in HB?
2. If you can capture a video stream to a file, you can use [Mediainfo](https://mediaarea.net/en/MediaInfo/Download#google_vignette) to look at the encoding.  
3. I assume the NVR is recording one of the streams.  My recollection is not all cameras support multiple simultaneous RTSP stream connections.

**Comment by BoazHarel1** [comment]
I know the encoding parameters that are defined in the camera output 
I don't know if there is a definition for the required encoding for the HB or HomeKit 

I wonder what is the meaning of the error code.

**Comment by ssb-kod** [comment]
> This also happened to me after I updated the HomeBridge from version 14 to version 16 and had to install all plugins from scratch, with Hikvision Cam model: DS-2CD2542FWD-I.
> 
> The previous Config were:
> 
> { "name": "Hikvision", "model": "DS-2CD2542FWD-I", "serialNumber": "DS-2CD2542FWD-#########", "firmwareRevision": "V5.5.5 build 180111", "unbridge": false, "videoConfig": { "source": "-i rtsp://**:**@192.168.10.10:554", "maxStreams": 2, "maxWidth": 800, "maxHeight": 600, "maxFPS": 25, "audio": true } }
> 
> The latest and working Config After noticing that I used a different model's setting by mistake [Hikvision DS-2CD2423G0-IW]:
> 
> { "name": "Hikvision", "videoConfig": { "source": "-i rtsp://**:**@192.168.10.10:554" } }
> 
> Thanks to developer [@Sunoo](https://github.com/Sunoo) for mentioning the matter here: "If maxWidth or maxHeight is set for more than 800 and 600 respectively or not set at all, the camera does not show the live view". In my case the mistake I made did result in me not being able to see Live View. For the reason that I entered the maxWidth and maxHeight values unnecessarily. https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Hikvision-DS-2CD2423G0-IW.html Now All Good : )

Thanks! This worked for me too in finally live streaming video via a TrueNAS core freebsd 13.3 jail. Previously event log ended with "FFmpeg exited with code: 0 and signal: null (Expected)" but just a spinning gear on Home app on our iPhones or MacBook. Snapshots every 12 seconds was working. Deleted all but the video source, vcodec, encodeOptions and debug parameters in the platforms > Camera FFmpeg > videoConfig subsection of my config.json and all is well, even to my Apple Watch, for live streams originating from an Amcrest camera substream.
